#!/bin/sh

set -e
for in in *.in; do
	tin="${in%.in}.tin.tmp"
	out="${in%.in}.out.tmp"
	ans="${in%.in}.ans"
	cp $in $tin
	while :; do
		echo
		echo s
	done | hardv $tin >/dev/null 2>$out || true
	diff -u $ans $out
done
