#!/bin/sh

set -e
for in in *.in; do
	n="${in%.in}.n"
	tin="`mktemp`"
	out="`mktemp`"
	ans="${in%.in}.ans"
	cp $in $tin
	while :; do
		echo
		echo s
	done | hardv -n "`cat $n`" $tin | grep ENTER \
		| wc -l | tr -d ' ' > $out
	diff -u $ans $out
done
