#!/bin/sh

set -e
chmod +x *.mod
for i in *.in; do
	ans=${i%.in}.ans
	act=${i%.in}.act
	out="`mktemp`"
	cp $i $out
	cat $act | \
	HARDV_NOW='2022-10-29 22:12:28 +0800' TZ='UTC-8' \
		hardv $out >/dev/null
	diff -u $ans $out
done
