#!/bin/sh

set -e
for in in *.in; do
	out="`mktemp`"
	ans=${in%.in}.ans
	act=${in%.in}.act
	arg=${in%.in}.arg
	now=${in%.in}.now
	cp $in $out
	<$act HARDV_NOW="`cat $now`" TZ='UTC-8'\
		hardv `cat $arg` $out >/dev/null
	diff -u $ans $out
done
