#!/bin/sh

set -e
for in in *.in; do
	tin="`mktemp`"
	out="`mktemp`"
	rout="`mktemp`"
	sout="`mktemp`"
	srout="`mktemp`"
	cp $in $tin
	while :; do
		echo
		echo s
	done | hardv -r $tin \
		| grep -v ENTER \
		| grep -v recall \
		| grep -v ^$ >$rout
	while :; do
		echo
		echo s
	done | hardv $tin \
		| grep -v ENTER \
		| grep -v recall \
		| grep -v ^$ >$out
	sort $out > $sout
	sort $rout > $srout
	! diff $out $rout >/dev/null
	diff $sout $srout
done
